#!/bin/bash
echo "=========================================="
echo "G1 训练环境提取验证报告"
echo "=========================================="
echo ""
echo "1. 文件统计："
echo "   - Python 文件: $(find . -name '*.py' -type f | wc -l) 个"
echo "   - XML 模型文件: $(find . -name '*.xml' -type f | wc -l) 个"
echo "   - 资源文件: $(find . -name '*.png' -type f | wc -l) 个"
echo ""
echo "2. 核心模块检查："
echo "   - g1_env 包: $([ -f g1_env/__init__.py ] && echo '✓' || echo '✗')"
echo "   - 环境注册表: $([ -f g1_env/_src/registry.py ] && echo '✓' || echo '✗')"
echo "   - G1 环境模块: $([ -f g1_env/_src/locomotion/g1/joystick.py ] && echo '✓' || echo '✗')"
echo "   - 训练脚本: $([ -f learning/train_jax_ppo.py ] && echo '✓' || echo '✗')"
echo ""
echo "3. 导入路径检查："
OLD_IMPORTS=$(grep -r "from mujoco_playground" . --include="*.py" 2>/dev/null | wc -l)
echo "   - 旧导入路径残留: $OLD_IMPORTS 处"
if [ "$OLD_IMPORTS" -eq 0 ]; then
    echo "   ✓ 所有导入路径已正确替换为 g1_env"
else
    echo "   ✗ 仍有未替换的导入路径"
fi
echo ""
echo "4. 项目配置："
echo "   - pyproject.toml: $([ -f pyproject.toml ] && echo '✓' || echo '✗')"
echo "   - README.md: $([ -f README.md ] && echo '✓' || echo '✗')"
echo "   - .gitignore: $([ -f .gitignore ] && echo '✓' || echo '✗')"
echo ""
echo "=========================================="
echo "提取完成！"
echo "=========================================="
echo ""
echo "下一步："
echo "1. 安装依赖: pip install -e ."
echo "2. 测试导入: python -c 'import g1_env; print(g1_env.registry.ALL_ENVS)'"
echo "3. 开始训练: train-g1-jax --env_name G1JoystickFlatTerrain"
